
/* generated by lolpig on 2016-12-29 16:23:29.793918 */

#include <python3.4/Python.h>



/* Call this before Py_Initialize() */
bool initialize_module_vec();

extern "C" {
    //struct VectorBase;
    //struct VectorIter;

    void vec_base_free(PyObject* self);
    PyObject* vec_base_getitem(PyObject* self, Py_ssize_t idx);
    Py_ssize_t vec_base_len(PyObject* self);
    PyObject* vec_base_repr(PyObject* self);
    PyObject* vec_base_new(_typeobject* type, PyObject* args, PyObject* );
    int vec_base_setitem(PyObject* self, Py_ssize_t idx, PyObject* val);

} // extern "C"


