
/* generated by lolpig on 2016-12-29 19:55:15.058228 */

#include <python3.4/Python.h>



/* Call this before Py_Initialize() */
bool initialize_module_vec();

extern "C" {
    /* class struct forwards */
    namespace MO {
    namespace PYTHON {
        struct VectorBase;
        struct VectorIter;
    } // namespace MO
    } // namespace PYTHON
    struct Some;

    namespace MO {
    namespace PYTHON {
        void vec_free(PyObject* self);
        PyObject* vec_getitem(PyObject* self, Py_ssize_t idx);
        Py_ssize_t vec_len(PyObject* self);
        PyObject* vec_new(_typeobject* type, PyObject* args, PyObject* );
        PyObject* vec_repr(PyObject* self);
        int vec_setitem(PyObject* self, Py_ssize_t idx, PyObject* val);
        PyObject* vec_test(PyObject* self, PyObject* args);
    } // namespace MO
    } // namespace PYTHON

} // extern "C"


