
/* generated by lolpig on 2016-12-29 22:46:15.899554 */

#ifndef LOLPIG_VEC_H_INCLUDED_
#define LOLPIG_VEC_H_INCLUDED_

#include <python3.4/Python.h>

namespace MOP {

    /* Call this before Py_Initialize() */
    bool initialize_module_vec();

} // namespace MOP

extern "C" {

    /* class struct forwards */
    struct Some;
    namespace MO {
    namespace PYTHON {
        struct VectorBase;
        struct VectorIter;
    } // namespace PYTHON
    } // namespace MO

    // global functions and class methods
    namespace MO {
    namespace PYTHON {
        PyObject* vec_copy(PyObject* self);
        void vec_free(PyObject* self);
        PyObject* vec_getitem(PyObject* self, Py_ssize_t idx);
        Py_ssize_t vec_len(PyObject* self);
        PyObject* vec_new(_typeobject* type, PyObject* args, PyObject* );
        PyObject* vec_repr(PyObject* self);
        int vec_setitem(PyObject* self, Py_ssize_t idx, PyObject* val);
        PyObject* vec_test(PyObject* , PyObject* args);
    } // namespace PYTHON
    } // namespace MO

} // extern "C"

#endif // LOLPIG_VEC_H_INCLUDED_
